
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Dizzy
 */
public class GUIFrame extends javax.swing.JFrame {
    private static String CustomerAdd;
    private static String CustomerComboinp;
    private static String FlightComboinp;
    private static String DayComboinp;
    private static int availableSeats;
    private static String seatLabel;
    
    private static String FlightComboinp2;
    private static String DayComboinp2;
    
    private static String DayComboinp3;
    private static ArrayList<String> array;
    private static ArrayList<String> array2;
    private static ArrayList<String> array3;
    private static ArrayList<String> array4;
    private static ArrayList<String> nextOnWait;
    
    private static String addedFlightName;
    private static String addedFlightSeats;
    //private static Integer addedFlightSeatsInt;
    
    private static Date DateString;
    
    private static String dropflightStr;
    
    private static String CustomerStat;
    private ArrayList<String> array5;
    private ArrayList<String> array6;
    
    
    private String dropped;
    
    /**
     * Creates new form GUIFrame
     */
    public GUIFrame() {
        initComponents();
        CustomerCombo1.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));  
        FlightCombo1.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
        DayCombo1.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
        DayCombo2.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
        FlightCombo2.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
        DayCombo3.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
        DropFlightBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));
        CustomerStatusBox.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
        
        
        TextArea1.setEditable(false);
        TextArea2.setEditable(false);
        TextArea3.setEditable(false);
        
        Field1.setEditable(false);
        Field2.setEditable(false);
        Field3.setEditable(false);
        Field4.setEditable(false);
        Field5.setEditable(false);
        Field6.setEditable(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TextField = new javax.swing.JTextField();
        AddCustomerButton = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        CustomerCombo1 = new javax.swing.JComboBox<>();
        FlightCombo1 = new javax.swing.JComboBox<>();
        DayCombo1 = new javax.swing.JComboBox<>();
        BookButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TextArea2 = new javax.swing.JTextArea();
        CancelButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        CheckStatusButton = new javax.swing.JButton();
        DayCombo2 = new javax.swing.JComboBox<>();
        FlightCombo2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TextArea3 = new javax.swing.JTextArea();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        field1 = new javax.swing.JPanel();
        DayCombo3 = new javax.swing.JComboBox<>();
        CheckWaitButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Field1 = new javax.swing.JTextField();
        Field2 = new javax.swing.JTextField();
        Field3 = new javax.swing.JTextField();
        Field4 = new javax.swing.JTextField();
        Field5 = new javax.swing.JTextField();
        Field6 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        AddNewFlightButton = new javax.swing.JButton();
        AddNewDayButton = new javax.swing.JButton();
        DateSpinner = new javax.swing.JSpinner();
        AddNewFlightSeats = new javax.swing.JTextField();
        AddNewFlightName = new javax.swing.JTextField();
        AddNewFlightLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        AddNewDayLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DropFlightBox = new javax.swing.JComboBox<>();
        DropFlightButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddDropText = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        CustomerStatusBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        f1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        d1 = new javax.swing.JTextField();
        f2 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        f3 = new javax.swing.JTextField();
        d3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        d4 = new javax.swing.JTextField();
        f5 = new javax.swing.JTextField();
        d5 = new javax.swing.JTextField();
        f4 = new javax.swing.JTextField();
        f6 = new javax.swing.JTextField();
        d6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Flight Scheduler");

        jLabel2.setText("Customer Name:");

        TextField.setText(" ");
        TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldActionPerformed(evt);
            }
        });

        AddCustomerButton.setText("Add");
        AddCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerButtonActionPerformed(evt);
            }
        });

        TextArea1.setColumns(20);
        TextArea1.setRows(5);
        jScrollPane8.setViewportView(TextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddCustomerButton)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddCustomerButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Customer", jPanel1);

        CustomerCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CustomerCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerCombo1ActionPerformed(evt);
            }
        });

        FlightCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FlightCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightCombo1ActionPerformed(evt);
            }
        });

        DayCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DayCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayCombo1ActionPerformed(evt);
            }
        });

        BookButton.setText("Book");
        BookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Customer:");

        jLabel4.setText("Flight:");

        jLabel5.setText("Day:");

        TextArea2.setColumns(20);
        TextArea2.setRows(5);
        jScrollPane7.setViewportView(TextArea2);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(FlightCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CustomerCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(DayCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(BookButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CancelButton)
                .addGap(311, 311, 311))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CustomerCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlightCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DayCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookButton)
                    .addComponent(CancelButton))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Booking", jPanel2);

        CheckStatusButton.setText("Check Status");
        CheckStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckStatusButtonActionPerformed(evt);
            }
        });

        DayCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DayCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayCombo2ActionPerformed(evt);
            }
        });

        FlightCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        FlightCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightCombo2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Day:");

        jLabel7.setText("Flight:");

        TextArea3.setColumns(20);
        TextArea3.setRows(5);
        jScrollPane6.setViewportView(TextArea3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(CheckStatusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FlightCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(DayCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(t5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(t6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DayCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FlightCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(59, 59, 59)
                        .addComponent(CheckStatusButton)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))))
        );

        jTabbedPane1.addTab("Status Flight Day", jPanel3);

        DayCombo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DayCombo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayCombo3ActionPerformed(evt);
            }
        });

        CheckWaitButton.setText("Check Waiting List");
        CheckWaitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckWaitButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Day:");

        javax.swing.GroupLayout field1Layout = new javax.swing.GroupLayout(field1);
        field1.setLayout(field1Layout);
        field1Layout.setHorizontalGroup(
            field1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(field1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(field1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(field1Layout.createSequentialGroup()
                        .addGroup(field1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, field1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DayCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CheckWaitButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(field1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(field1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Field5, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                            .addGroup(field1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(field1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Field3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Field4)))))
                    .addComponent(Field6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(field1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Field1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addComponent(Field2, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        field1Layout.setVerticalGroup(
            field1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(field1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Field1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(field1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DayCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(Field3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(field1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(field1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CheckWaitButton))
                    .addGroup(field1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Field4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Field5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Field6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Status Waitlist", field1);

        AddNewFlightButton.setText("Add");
        AddNewFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewFlightButtonActionPerformed(evt);
            }
        });

        AddNewDayButton.setText("Add");
        AddNewDayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewDayButtonActionPerformed(evt);
            }
        });

        DateSpinner.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        AddNewFlightSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewFlightSeatsActionPerformed(evt);
            }
        });

        AddNewFlightName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewFlightNameActionPerformed(evt);
            }
        });

        AddNewFlightLabel.setText("Add New Flight");

        jLabel10.setText("Flight Name:");

        jLabel11.setText("# of Seats:");

        AddNewDayLabel.setText("Add New Day");

        jLabel12.setText("Drop Flight");

        DropFlightBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DropFlightButton.setText("Drop");
        DropFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropFlightButtonActionPerformed(evt);
            }
        });

        AddDropText.setColumns(20);
        AddDropText.setRows(5);
        jScrollPane1.setViewportView(AddDropText);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddNewFlightName))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AddNewFlightButton)
                                    .addComponent(AddNewFlightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AddNewFlightSeats))))
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DropFlightButton)
                    .addComponent(DropFlightBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddNewDayLabel)
                    .addComponent(AddNewDayButton)
                    .addComponent(jLabel12))
                .addGap(16, 16, 16))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddNewFlightLabel)
                            .addComponent(AddNewDayLabel))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddNewFlightName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(DateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddNewFlightSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(AddNewDayButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddNewFlightButton)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(DropFlightBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DropFlightButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add/Drop", jPanel4);

        CustomerStatusBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CustomerStatusBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerStatusBoxActionPerformed(evt);
            }
        });

        jLabel9.setText("Select Customer:");

        jLabel13.setText("Bookings");

        jLabel14.setText("Waitlist");

        jLabel15.setText("Flight");

        jLabel16.setText("Day");

        jLabel17.setText("Flight");

        jLabel18.setText("Day");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(123, 123, 123)
                        .addComponent(jLabel13)
                        .addGap(132, 132, 132)
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(CustomerStatusBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(f1)
                                        .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(d3)
                                    .addComponent(d2)
                                    .addComponent(d1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(f4)
                                    .addComponent(f5, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(f6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(d6)
                                    .addComponent(d5)
                                    .addComponent(d4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jLabel15)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel18)
                                .addGap(61, 61, 61)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(f3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(f4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(f5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(f6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(CustomerStatusBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Status Customer", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckWaitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckWaitButtonActionPerformed
        // TODO add your handling code here:
        DayComboinp3 = DayCombo3.getSelectedItem().toString();
        array = Waitlist.getWaitlist(DayComboinp3);
        try{
            Field1.setText(array.get(0));
        }
        catch (Exception t){
            Field1.setText(" ");
        }
        try{
            Field2.setText(array.get(1));
        }
        catch (Exception t){
            Field2.setText(" ");
        }
        try{
            Field3.setText(array.get(2));
        }
        catch (Exception t){
            Field3.setText(" ");
        }
        try{
            Field4.setText(array.get(3));
        }
        catch (Exception t){
            Field4.setText(" ");
        }
        try{
            Field5.setText(array.get(4));
        }
        catch (Exception t){
            Field5.setText(" ");
        }
        try{
            Field6.setText(array.get(5));
        }
        catch (Exception t){
            Field6.setText(" ");
        }
    }//GEN-LAST:event_CheckWaitButtonActionPerformed

    private void DayCombo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayCombo3ActionPerformed
        // TODO add your handling code here:
        DayComboinp3 = DayCombo3.getSelectedItem().toString();
    }//GEN-LAST:event_DayCombo3ActionPerformed

    private void FlightCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightCombo2ActionPerformed
        // TODO add your handling code here:
        FlightComboinp2 = FlightCombo2.getSelectedItem().toString();
    }//GEN-LAST:event_FlightCombo2ActionPerformed

    private void DayCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayCombo2ActionPerformed
        // TODO add your handling code here:
        DayComboinp2 = DayCombo2.getSelectedItem().toString();
    }//GEN-LAST:event_DayCombo2ActionPerformed

    private void CheckStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckStatusButtonActionPerformed
        DayComboinp2 = DayCombo2.getSelectedItem().toString();
        FlightComboinp2 = FlightCombo2.getSelectedItem().toString();
        if (BookingEntry.bookingCounter(FlightComboinp2, DayComboinp2) >= BookingEntry.seatCounter(FlightComboinp2)){
            TextArea3.setText("flight is full");
            //check waitlist
            //list customers on flight
        }
        else {
            seatLabel = "Flight " + FlightComboinp2 + " has ";
            availableSeats = BookingEntry.seatCounter(FlightComboinp2) - BookingEntry.bookingCounter(FlightComboinp2, DayComboinp2);
            seatLabel = seatLabel + String.valueOf(availableSeats) + " available seats.";
            TextArea3.setText(seatLabel);
        }
        array2 = BookingEntry.getFlightCustomers(FlightComboinp2, DayComboinp2);
        try{
            t1.setText(array2.get(0));
        }
        catch (Exception t){
            t1.setText(" ");
        }
        try{
            t2.setText(array2.get(1));
        }
        catch (Exception t){
            t2.setText(" ");
        }
        try{
            t3.setText(array2.get(2));
        }
        catch (Exception t){
            t3.setText(" ");
        }
        try{
            t4.setText(array2.get(3));
        }
        catch (Exception t){
            t4.setText(" ");
        }
        try{
            t5.setText(array2.get(4));
        }
        catch (Exception t){
            t5.setText(" ");
        }
        try{
            t6.setText(array2.get(5));
        }
        catch (Exception t){
            t6.setText(" ");
        }

    }//GEN-LAST:event_CheckStatusButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        try {            
            DayComboinp2 = DayCombo2.getSelectedItem().toString();
            BookingEntry.deleteEntry(CustomerComboinp, DayComboinp);
            nextOnWait = Waitlist.getNextCustomers(FlightComboinp, DayComboinp);
            BookingEntry.addBook(nextOnWait.get(0), FlightComboinp, DayComboinp);
            Waitlist.deleteEntry(nextOnWait.get(0), FlightComboinp, DayComboinp);
            //System.out.println(CustomerAdd + " " + FlightComboinp + " " + DayComboinp);
        } catch (SQLException ex) {
            //Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    CustomerCombo1.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));  
    FlightCombo1.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
    DayCombo1.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
    DayCombo2.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
    FlightCombo2.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
    DayCombo3.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
    DropFlightBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));  
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void BookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookButtonActionPerformed
        try{
            // TODO add your handling code here:
            
            DayComboinp = DayCombo1.getSelectedItem().toString();
            FlightComboinp = FlightCombo1.getSelectedItem().toString();
            CustomerComboinp = CustomerCombo1.getSelectedItem().toString();
            
            if (BookingEntry.bookingCounter(FlightComboinp, DayComboinp) >= BookingEntry.seatCounter(FlightComboinp)){
                TextArea2.setText("Flight is already full we will put you on the waitlist");
                Waitlist.addWaitlist(CustomerComboinp, FlightComboinp, DayComboinp);
            }
            else {
                BookingEntry.addBook(CustomerComboinp, FlightComboinp, DayComboinp);
                TextArea2.setText("Customer booked for flight");
            }
        }
        catch (Exception f){

            TextArea2.setText("Make sure to click enter on every selection");

        }
    CustomerCombo1.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));  
    FlightCombo1.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
    DayCombo1.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
    DayCombo2.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
    FlightCombo2.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
    DayCombo3.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
    DropFlightBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));  
    }//GEN-LAST:event_BookButtonActionPerformed

    private void DayCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayCombo1ActionPerformed
        // TODO add your handling code here:

        DayComboinp = DayCombo1.getSelectedItem().toString();

    }//GEN-LAST:event_DayCombo1ActionPerformed

    private void FlightCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightCombo1ActionPerformed
        // TODO add your handling code here:
        FlightComboinp = FlightCombo1.getSelectedItem().toString();
    }//GEN-LAST:event_FlightCombo1ActionPerformed

    private void CustomerCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerCombo1ActionPerformed
        // TODO add your handling code here:
        CustomerComboinp = CustomerCombo1.getSelectedItem().toString();
    }//GEN-LAST:event_CustomerCombo1ActionPerformed

    private void AddCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerButtonActionPerformed
        try {
            
            //FlightComboinp2 = DayCombo3.getSelectedItem().toString();
            CustomerAdd = TextField.getText();
            Customer.addNewCustomer(CustomerAdd); // TODO add your handling code here:
            CustomerCombo1.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));
            TextArea1.setText("Customer Name has been entered into database");
        }
        catch (NumberFormatException i){

        }
    CustomerCombo1.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));  
    FlightCombo1.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
    DayCombo1.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
    DayCombo2.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
    FlightCombo2.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
    DayCombo3.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
    DropFlightBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));  
    }//GEN-LAST:event_AddCustomerButtonActionPerformed

    private void TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldActionPerformed
        try {
            CustomerAdd = TextField.getText();

        }
        catch (NumberFormatException i){
        }
    }//GEN-LAST:event_TextFieldActionPerformed

    private void AddNewFlightNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewFlightNameActionPerformed
        try {addedFlightName = AddNewFlightName.getText();
        
        }
        catch (NumberFormatException i){
            
        }
        
    }//GEN-LAST:event_AddNewFlightNameActionPerformed

    private void AddNewFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewFlightButtonActionPerformed
            
        try{
            addedFlightName = AddNewFlightName.getText();
            addedFlightSeats = AddNewFlightSeats.getText();
            //addedFlightSeatsInt = Integer.parseInt(addedFlightSeats);
            Flight.addFlight(addedFlightName, addedFlightSeats);
            //System.out.println(addedFlightName + " " + addedFlightSeats);
            FlightCombo1.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
            DayCombo1.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
            AddDropText.setText("Flight " + addedFlightName + " has been Added");
        }
        catch (NumberFormatException i){
            
        }
    CustomerCombo1.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));  
    FlightCombo1.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
    DayCombo1.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
    DayCombo2.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
    FlightCombo2.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
    DayCombo3.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
    DropFlightBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));  
    }//GEN-LAST:event_AddNewFlightButtonActionPerformed

    private void AddNewFlightSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewFlightSeatsActionPerformed
        try {
            addedFlightSeats = AddNewFlightSeats.getText();
        }
        catch (NumberFormatException i){
            
        }
    CustomerCombo1.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));  
    FlightCombo1.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
    DayCombo1.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
    DayCombo2.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
    FlightCombo2.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
    DayCombo3.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
    DropFlightBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));   
    }//GEN-LAST:event_AddNewFlightSeatsActionPerformed

    private void AddNewDayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewDayButtonActionPerformed
        DateString = (Date) DateSpinner.getValue();
        //System.out.println(DateString);
        Day.addNewDay(DateString);
        AddDropText.setText("Day has been added");
        
        CustomerCombo1.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));  
        FlightCombo1.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
        DayCombo1.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
        DayCombo2.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
        FlightCombo2.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
        DayCombo3.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
        DropFlightBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));  
    }//GEN-LAST:event_AddNewDayButtonActionPerformed

    private void DropFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropFlightButtonActionPerformed
        dropflightStr = DropFlightBox.getSelectedItem().toString();
        //try {
            //System.out.println(dropflightStr);
            ArrayList<String> arrayDay = Day.getDays();
            ArrayList<ArrayList> droppedArray = new ArrayList<ArrayList>();
            //System.out.println(arrayDay);
            for (int i = 0; i < (arrayDay.size() ); i++){
                //System.out.println(arrayDay.get(i));
                if (i > 0) {
                        //System.out.println(dropflightStr);
                        //System.out.println(arrayDay.get(i));
                        //System.out.println(droppedArray);
                        //System.out.println(BookingEntry.getFlightCustomers(dropflightStr, arrayDay.get(i))); 
                        droppedArray.add(BookingEntry.getFlightCustomers(dropflightStr, arrayDay.get(i)));
                }
            }
            System.out.println(droppedArray);
            for (int i = 0; i < (arrayDay.size() ); i++){
                if (BookingEntry.bookingCounter(dropflightStr, arrayDay.get(i)) >= BookingEntry.seatCounter(dropflightStr)){
                    try{
                        BookingEntry.addBook((String) droppedArray.get(i).get(i), FlightComboinp, DayComboinp);
                    }
                    catch (Exception z){
            
        }
                    
                }
                    
    }
            //Waitlist.deleteCustomersFlight(dropflightStr);
            //Flight.removeFlight(dropflightStr);
            dropped = "Flight " + dropflightStr + " has been dropped."
                    + " The following customers were unable to be rebooked: ";
            
            //add each customer able to be booked to dropped string
            
            AddDropText.setText(dropped);
        //}
        //catch (SQLException ex) {
          //  Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        //}
            CustomerCombo1.setModel(new javax.swing.DefaultComboBoxModel(Customer.getAllCustomers().toArray()));  
            FlightCombo1.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
            DayCombo1.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
            DayCombo2.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
            FlightCombo2.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray())); 
            DayCombo3.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
            DropFlightBox.setModel(new javax.swing.DefaultComboBoxModel(Flight.getFlightNames().toArray()));       
    }//GEN-LAST:event_DropFlightButtonActionPerformed

    private void CustomerStatusBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerStatusBoxActionPerformed
        CustomerStat = (String) CustomerStatusBox.getSelectedItem();
        try {
            array3 = BookingEntry.getCustomerInfo(CustomerStat);
        } catch (SQLException ex) {
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        //System.out.printl n(CustomerStat);
        try{
            f1.setText(array3.get(0));
        }
        catch (Exception t){
            f1.setText(" ");
        }
        try{
            f2.setText(array3.get(1));
        }
        catch (Exception t){
            f2.setText(" ");
        }
        try{
            f3.setText(array3.get(2));
        }
        catch (Exception t){
            f3.setText(" "); 
        }
        
        
        try {
            array4 = BookingEntry.getCustomerDays(CustomerStat);
        } catch (SQLException ex) {
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
                try{
            d1.setText(array4.get(0));
        }
        catch (Exception t){
            d1.setText(" ");
        }
        try{
            d2.setText(array4.get(1));
        }
        catch (Exception t){
            d2.setText(" ");
        }
        try{
            d3.setText(array4.get(2));
        }
        catch (Exception t){
            d3.setText(" "); 
        }
        try {
            array5 = Waitlist.getCustomerInfo(CustomerStat);
        } catch (SQLException ex) {
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
            f4.setText(array5.get(0));
        }
        catch (Exception t){
            f4.setText(" ");
        }
        try{
            f5.setText(array5.get(1));
        }
        catch (Exception t){
            f5.setText(" ");
        }
        try{
            f6.setText(array5.get(2));
        }
        catch (Exception t){
            f6.setText(" "); 
        }
        
        try {
            array6 = Waitlist.getCustomerDays(CustomerStat);
        } catch (SQLException ex) {
            Logger.getLogger(GUIFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try{
            d4.setText(array6.get(0));
        }
        catch (Exception t){
            d4.setText(" ");
        }
        try{
            d5.setText(array6.get(1));
        }
        catch (Exception t){
            d5.setText(" ");
        }
        try{
            d6.setText(array6.get(2));
        }
        catch (Exception t){
            d6.setText(" "); 
        }
        
    }//GEN-LAST:event_CustomerStatusBoxActionPerformed

    
        
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCustomerButton;
    private javax.swing.JTextArea AddDropText;
    private javax.swing.JButton AddNewDayButton;
    private javax.swing.JLabel AddNewDayLabel;
    private javax.swing.JButton AddNewFlightButton;
    private javax.swing.JLabel AddNewFlightLabel;
    private javax.swing.JTextField AddNewFlightName;
    private javax.swing.JTextField AddNewFlightSeats;
    private javax.swing.JButton BookButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CheckStatusButton;
    private javax.swing.JButton CheckWaitButton;
    private javax.swing.JComboBox<String> CustomerCombo1;
    private javax.swing.JComboBox<String> CustomerStatusBox;
    private javax.swing.JSpinner DateSpinner;
    private javax.swing.JComboBox<String> DayCombo1;
    private javax.swing.JComboBox<String> DayCombo2;
    private javax.swing.JComboBox<String> DayCombo3;
    private javax.swing.JComboBox<String> DropFlightBox;
    private javax.swing.JButton DropFlightButton;
    private javax.swing.JTextField Field1;
    private javax.swing.JTextField Field2;
    private javax.swing.JTextField Field3;
    private javax.swing.JTextField Field4;
    private javax.swing.JTextField Field5;
    private javax.swing.JTextField Field6;
    private javax.swing.JComboBox<String> FlightCombo1;
    private javax.swing.JComboBox<String> FlightCombo2;
    private javax.swing.JTextArea TextArea1;
    private javax.swing.JTextArea TextArea2;
    private javax.swing.JTextArea TextArea3;
    private javax.swing.JTextField TextField;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField d3;
    private javax.swing.JTextField d4;
    private javax.swing.JTextField d5;
    private javax.swing.JTextField d6;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f3;
    private javax.swing.JTextField f4;
    private javax.swing.JTextField f5;
    private javax.swing.JTextField f6;
    private javax.swing.JPanel field1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    // End of variables declaration//GEN-END:variables
}
